std::map<SDL_Keycode, int> index = {
    /* physical key     piano key index */
    /* white keys */
    { SDLK_q,			3 },
    { SDLK_w,			4 },
    { SDLK_e,			5 },
    { SDLK_r,			6 },
    { SDLK_t,			7 },
    { SDLK_y,			8 },
    { SDLK_u,			9 },
    { SDLK_i,			10 },
    { SDLK_o,			11 },
    { SDLK_p,			12 },
    { SDLK_LEFTBRACKET,	13 },
    { SDLK_RIGHTBRACKET,14 },
    { SDLK_1,			15 },
    { SDLK_z,			16 },
    { SDLK_x,			17 },
    { SDLK_c,			18 },
    { SDLK_v,			19 },
    { SDLK_b,			20 },
    { SDLK_n,			21 },
    { SDLK_m,			22 },
    { SDLK_COMMA,		23 },
    { SDLK_PERIOD,		24 },
    { SDLK_SLASH,		25 },

    /* black keys */
    { SDLK_2,			34 },
    { SDLK_3,			35 },
    { SDLK_4,			36 },
    { SDLK_5,			38 },
    { SDLK_7,			39 },
    { SDLK_8,			41 },
    { SDLK_0,			42 },
    { SDLK_MINUS,		43 },
    { SDLK_EQUALS,		45 },
    { SDLK_a,			46 },
    { SDLK_s,			48 },
    { SDLK_f,			49 },
    { SDLK_g,			50 },
    { SDLK_h,			52 },
    { SDLK_k,			53 },
    { SDLK_l,			55 },
    { SDLK_QUOTE,		56 },
};

